{% set version = "2.0.13" %}

package:
  name: bob.learn.activation
  version: {{ version }}

source:
  fn: bob.learn.activation-{{ version }}.zip
  md5: 99e73cb0db939a229f68413727b3a150
  url: https://pypi.io/packages/source/b/bob.learn.activation/bob.learn.activation-{{ version }}.zip

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - python
    - toolchain
    - setuptools
    - bob.extension >2.0.4
    - bob.blitz
    - bob.core
    - bob.io.base
    - boost 1.61.*
    - cmake
    - pkg-config

  run:
    - python
    - bob.extension >2.0.4
    - bob.blitz
    - bob.core
    - bob.io.base
    - boost 1.61.*

test:
  commands:
    - nosetests -sv bob.learn.activation

  imports:
    - bob
    - bob.learn
    - bob.learn.activation

  requires:
    - nose

about:
  home: https://www.idiap.ch/software/bob/
  license: Modified BSD License (3-clause)
  summary: Bindings for bob.machine's Activation functors

extra:
  recipe-maintainers:
    - 183amir
